### ISSUE TITLE
[Docs] API 초안 작성

### ISSUE THREAD

**Issue by sjmjys954646** [softeerbootcamp-3rd/Team4-HansalChai#1]
## Description
API 초안 작성

## Estimated Duration
2월 2일 금요일 ~ 2월 5일 월요일 (4일)

## TO-DO
- [x] API 초안 / 예약 고객 @sjmjys954646 
- [x] API 초안 / 회원가입, 로그인 및 프로필 @sjmjys954646 
- [x] API 초안 / 예약 비회원 @sjmjys954646 
- [x] API 초안 / 예약 기사 @jiaeYoon @sjmjys954646

**Comment by sjmjys954646** [comment]
@sean2337 @Pransinia 호출

**Comment by sjmjys954646** [comment]
@Pransinia @sean2337 REST API 리뷰하고 
https://github.com/softeerbootcamp-3rd/Team4-HansalChai/discussions/12
에 의견 남겨주세요
