### ISSUE TITLE
[Fix] 고객 요청 버그들 수정 후 배포

### ISSUE THREAD

**Issue by sjmjys954646** [softeerbootcamp-3rd/Team4-HansalChai#113]
## Description
고객 요청 버그들 수정 후 배포

## Estimated Duration
2월 17일 토요일 ~ 2월 17일 토요일 (1일)

## TO-DO
- [x] 필터에서 whitelist 변경
- [x] 트럭 정보 cm->m 자르기
- [x] null return string -> object
- [x] 예약완료 예약전 요청 분리
- [x] 예약전인건 select안되게 변경
