### ISSUE TITLE
[Feat] (기사) 페이지 퍼블리싱 완료 테스트 작업

### ISSUE THREAD

**Issue by sean2337** [softeerbootcamp-3rd/Team4-HansalChai#125]
## Description
@sean2337  @Pransinia 이 페이지 퍼블리싱 작업이 1차적으로 완료되었고, 이를 합치면서 기타 수정 사항들을 수정합니다.  

## Estimated Duration
2월 18일 일요일 (1일)

## TO-DO
- [x] 디자인 CSS 수정
- [x] 페이지 로직 생성 및 적용
- [x] 기타 수정 사항 체크
- [x] 테스트
