### ISSUE TITLE
[Feat] (기사) 기사버전 기획 변경에 따른 퍼블리싱 수정

### ISSUE THREAD

**Issue by sean2337** [softeerbootcamp-3rd/Team4-HansalChai#128]
## Description
기사버전 기획이 변경됨에 따라 이에 따라 퍼블리싱을 다시 작업합니다. 

## Estimated Duration
2월 18일 일요일 (1일)

## TO-DO
- [x] HaulInfoBox 컴포넌트 퍼블리싱
- [x] 기사 출발 도착 버튼 컴포넌트 생성 및 로직 추가 (API제외)
- [x] 기타 CSS 수정
