### ISSUE TITLE
[Feat] (기사) 기사버전 API 연동 - sean2337

### ISSUE THREAD

**Issue by sean2337** [softeerbootcamp-3rd/Team4-HansalChai#131]
## Description
@sean2337 이 맡은 기사버전 API 연동을 시작합니다.

## Estimated Duration
2월 18일 월요일 (1일)

## TO-DO
- [x] 주문 승인 API 연동
- [x] 주문 상세 페이지 데이터 불러오기 API 연동
- [x] 내 일정 상세 페이지 데이터 불러오기
- [x] 내 일정 status 변화시키는 API 연동
