### ISSUE TITLE
[Feat] (기사) 기사버전 코드 분리 및 리팩토링 - sean2337

### ISSUE THREAD

**Issue by sean2337** [softeerbootcamp-3rd/Team4-HansalChai#137]
## Description
@sean2337 이 담당한 페이지에 대해 코드를 분리하고 리팩토링 작업을 진행합니다. 

## Estimated Duration
2월 19일 월요일 (1일)

## TO-DO
- [x] 로그인 페이지 코드 분리 및 리팩토링
- [x] 나의 운송 상세 보기 페이지 분리 및 리팩토링
- [x] 일정 잡기 상세 보기 페이지 분리 및 리팩토링
- [x] 일정 잡기 완료 페이지 분리 및 리팩토링
