### ISSUE TITLE
[Refactor] 고객버전 리팩토링 작업

### ISSUE THREAD

**Issue by sean2337** [softeerbootcamp-3rd/Team4-HansalChai#141]
## Description
고객 버전 리팩토링 작업을 수행합니다. 

## Estimated Duration
2월 19일 월요일 (1일)

## TO-DO
- [x] 로그인 안되었을때 Router에서 이를 조절함 ( 모든 페이지에서 로그인 했는지를 다루지 않게 변경 ) 
- [x] 지도 버그 수정
- [x] 전체 템플릿과 메인로직 코드 분리
