### ISSUE TITLE
[FEAT] 기사버전 예외처리

### ISSUE THREAD

**Issue by sean2337** [softeerbootcamp-3rd/Team4-HansalChai#170]
## Description
기사 버전의 예외 처리를 진행합니다. 
## Estimated Duration
2월 20일 화(1일)

## TO-DO
- [x] 로그인 예외처리
- [x] 일정 상세 보기 예외처리
- [x] 일정 잡기 상세 보기 예외처리
- [x] 운송 상태 변경 예외처리
