### ISSUE TITLE
[Enhance] 성능 개선, 테스트코드추가, 프론트 요청 사항 추가

### ISSUE THREAD

**Issue by sjmjys954646** [softeerbootcamp-3rd/Team4-HansalChai#207]
## Description
성능 개선, 테스트코드추가, 프론트 요청 사항 추가

## Estimated Duration
2월 22일 목요일 ~ 2월 23일 금요일 (2일)

## TO-DO
- [x] 테스트코드 추가
- [x] 무게 double로 변경
- [x] 테스트 생성기 생성
- [x] distance 로직 확인
