### ISSUE TITLE
[Enhance] 고객 버전 최종 성능 개선 

### ISSUE THREAD

**Issue by sean2337** [softeerbootcamp-3rd/Team4-HansalChai#222]
## Description
고객 버전 최종 성능 개선 작업을 진행합니다. 

## Estimated Duration
2월 23일 금요일 ~ 2월 24일 토요일 (2일)

## TO-DO
- [x] 고객 버전 최종 성능 개선 작업을 진행합니다. 
- [x] 스플래쉬 창에서 기존 로그인 세션 스토리지 제거 작업
- [x] 마지막 CSS를 수정합니다
