### ISSUE TITLE
[Refactor] 최종 버그 수정 및 리팩토링

### ISSUE THREAD

**Issue by sean2337** [softeerbootcamp-3rd/Team4-HansalChai#232]
## Description
최종 버그 수정 및 리팩토링를 진행합니다.

## Estimated Duration
2월 24일 토 (1일)

## TO-DO
- [x] 고객 버전 마무리
- [x] 기사 버전 마무리
- [x] 설문지 피드백 적용
