### ISSUE TITLE
[Feat] 2/8 데모 전 1차 페이지 구현

### ISSUE THREAD

**Issue by sean2337** [softeerbootcamp-3rd/Team4-HansalChai#24]
## Description
고객 버전의 Houl 서비스 페이지를 1차로 개발합니다. (목요일 데모 전까지)
API연동을 고려하여 페이지 컴포넌트를 개발합니다. 
프론트엔드 개발자끼리 페이지 분배를 진행하였고, 이에 대해 각자 개발하고 리뷰를 진행하여 개선된 코드를 만들어냅니다. 
만약 각자 끝났다면 다른 팀원의 페이지 개발을 도와서 진행합니다. 

## Estimated Duration
2월 6일 화요일 ~ 2월 11일 목요일 (3일)

## TO-DO
- [x] Splash 페이지
- [x] Login 페이지
- [x] GuestLogin 페이지
- [x] 회원가입 페이지
- [x] 운송 종류 선택 페이지
- [x] 날짜 선택 페이지
- [x] 시간 선택 페이지
- [x] 출발지 장소 선택 페이지
- [x] 도착지 장소 선택 페이지
- [x] 적재량 정보 입력 페이지
