### ISSUE TITLE
[Feat] 2/8 데모 전 1차 페이지 구현 - Pransinia

### ISSUE THREAD

**Issue by Pransinia** [softeerbootcamp-3rd/Team4-HansalChai#29]
## Description
목요일 데모 전까지 고객 버전의 Houl 서비스 페이지를 1차로 개발합니다.
API연동을 고려하여 페이지 컴포넌트를 개발합니다.
프론트엔드 개발자끼리 페이지 분배를 진행하였고, 이에 대해 각자 개발하고 리뷰를 진행하여 개선된 코드를 만들어냅니다. 
만약 각자 끝났다면 다른 팀원의 페이지 개발을 도와서 진행합니다.

## Estimated Duration
2월 6일 화요일 ~ 2월 8일 목요일 (3일)

## TO-DO
- [x] 더보기 페이지
- [x] 내 정보 페이지
- [x] 내 결제수단 페이지
- [x] 약관 리스트 페이지
- [x] 약관 상세 페이지
- [x] 예약 리스트 선택 페이지
- [x] 내역 상세 확인 페이지

**Comment by Pransinia** [comment]
#47 의 머지 성공으로 닫겠습니다.

close #29
