### ISSUE TITLE
[Feat] FE 초기 세팅 작업

### ISSUE THREAD

**Issue by sean2337** [softeerbootcamp-3rd/Team4-HansalChai#4]
## Description
`Vite` 를 통한 프로젝트 생성 및 기타 세팅 작업

## Estimated Duration
2월 3일 토요일 ~ 2월 4일 수요일 (2일)

## TO-DO
- [x] Vite를 통한 프로젝트 생성 및 폴더 구조 잡기(PWA기능 포함) @Pransinia 
- [x] React-Router 적용을 통한 페이지 이동 세팅 @sean2337 
- [x] Global Style 생성 및 테마 적용 @sean2337
