### ISSUE TITLE
[Feat] 결과 페이지 구현 및 카카오맵 적용

### ISSUE THREAD

**Issue by sean2337** [softeerbootcamp-3rd/Team4-HansalChai#42]
## Description
결과 페이지의 퍼블리싱과 로직을 완료합니다. (API제외)
이때 지도의 경우, 현재는 구글맵이 적용 되어있는데 카카오맵으로 변경합니다. 
또한 결제 완료 페이지까지 구현합니다. 

## Estimated Duration
2월 10일 토요일 ~ 2월 11일 일요일 (2일)

## TO-DO
- [x] 결과 페이지 퍼블리싱
- [x] DetailInfo Remake => 카카오맵으로 변경
- [x] 결제 완료 페이지 구현
