### ISSUE TITLE
[Feat] Request 로직 예외처리 및 리팩토링 작업

### ISSUE THREAD

**Issue by sean2337** [softeerbootcamp-3rd/Team4-HansalChai#45]
## Description
Request 영역에서의 모든 페이지의 예외처리 로직을 추가합니다. 
또한 코드 리팩토링을 진행합니다. 
API 적용 전까지의 코드 상태를 정리합니다. 
Request부분 아니더라도 API 적용 전에 전체 코드에 대한 리팩토링 작업을 진행합니다.

## Estimated Duration
2월 11일 일요일 ~ 2월 12일 월요일 (2일)

## TO-DO
- [x] 공용 컴포넌트 리팩토링
- [x] 회원가입 페이지 예외처리 및 리팩토링 작업
- [x] 로그인 페이지 예외처리 및 리팩토링 작업
- [x] 비회원로그인 페이지 예외처리 및 리팩토링 작업
- [x] 운송종류선택 페이지 예외처리 및 리팩토링 작업
- [x] 날짜 선택 페이지 예외처리 및 리팩토링 작업
- [x] 시간 선텍 페이지 예외처리 및 리팩토링 작업
- [x] 출발지 선택 페이지 예외처리 및 리팩토링 작업
- [x] 도착지 선택 페이지 예외처리 및 리팩토링 작업
- [x] 적재량 정보 페이지 예외처리 및 리팩토링 작업
- [x] 결과 페이지 예외처리 및 리팩토링 작업
