### ISSUE TITLE
[Docs] 디자인 설계

### ISSUE THREAD

**Issue by Pransinia** [softeerbootcamp-3rd/Team4-HansalChai#5]
## Description
<strong>Haul</strong>의 디자인 설계
[Figma](https://www.figma.com/file/XFcD5JjGJMRJ3OuGmyqP1z/%EB%94%94%EC%9E%90%EC%9D%B8?type=design&node-id=0%3A1&mode=dev&t=o7kT92NiyqlBsu5x-1)

## Estimated Duration
2월 1일 목요일 ~ 2월 3일 토요일 (3일)

## TO-DO
- [x] 디자인 시스템 작성 @sean2337 
- [x] 메인 플로우 디자인 작성 @sean2337 
- [x] 더보기 디자인 작성 @Pransinia
