### ISSUE TITLE
[Feat] 구현사항 리팩터링 - 고객앱

### ISSUE THREAD

**Issue by Pransinia** [softeerbootcamp-3rd/Team4-HansalChai#52]
## Description
고객 앱에 구현했던 컴포넌트와 페이지 전체에 대한 회고와 리팩터링을 실시합니다.

## Estimated Duration
2월 12일 월요일 ~ 2월 14일 수요일 (3일)

## TO-DO
고객 앱
- [x] 컴포넌트 - 캐로셀
- [x] 컴포넌트 - 네비게이션바
- [x] 컴포넌트 - 하단 버튼
- [x] 컴포넌트 - 토스트
- [x] 컴포넌트 - 헤더
- [x] 컴포넌트 - 무한 스크롤
- [x] 페이지    - 더보기 리스트
- [x] 페이지    - 유저 정보
- [x] 페이지    - 결제 정보
- [x] 페이지    - 약관 상세
- [x] 페이지    - 예약 리스트
- [x] 페이지    - 예약 상세

## 고칠 것
- [x] 네비게이션 바 - 아이콘 크기가 다름
- [x] 토스트 - 레이아웃을 벗어나거나 메세지가 아이콘을 침범하는 문제 해결
