### ISSUE TITLE
[Feat] 프로필 기능 구현

### ISSUE THREAD

**Issue by jiaeYoon** [softeerbootcamp-3rd/Team4-HansalChai#60]
## Description
프로필 조회, 수정 기능을 구현합니다.

## Estimated Duration
2월 14일 수요일 (1일)

## TO-DO
- [ ] 프로필 조회 기능 구현
- [ ] 프로필 수정 기능 구현
- [ ] 테스트 코드 작성
