### ISSUE TITLE
[Feat] 1차 배포를 위한 수정 작업 및 문서화 작업

### ISSUE THREAD

**Issue by sean2337** [softeerbootcamp-3rd/Team4-HansalChai#95]
## Description
1차 배포를 하기 전에 수정 작업 및 문서화를 진행합니다. 이때 문서화는 파일 별 readme.md 추가를 말합니다. 

## Estimated Duration
2월 15일 월요일 ~ 2월 15일 수요일 (1일)

## TO-DO
- [x] 적재량 운송 종류에 따른 예외처리
- [x] 공용 컴포넌트 readme.md 추가
- [x] 페이지 별 readme.md 추가
- [x] 고객 Haul 배포 및 체크
